apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-traefik-forward-auth
  namespace: flux-system
spec:
  interval: 1h
  path: ./cluster/apps/networking/traefik-forward-auth/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
