apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-release
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: networking
    app.kubernetes.io/component: ingress-controller
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.15.2
    chart: metallb
  sources: []
  project: networking
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true