apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
  namespace: media
spec:
  ports:
  - name: jellyfin-app
    port: 80
    protocol: TCP
    targetPort: 80
  clusterIP: None
  type: ClusterIP