apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: 2.8.4
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  dependsOn:
    - name: ingress-nginx-external
      namespace: networking
  values:
    replicas: 1
    hostname: rancher.${SECRET_LOCAL_DOMAIN}
    bootstrapPassword: "${SECRET_RANCHER_ADMIN_PASSWORD}"