apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-jackett
  namespace: flux-system
spec:
  interval: 1h
  path: ./clusters/my-cluster/apps/media/jackett/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:            
    provider: sops       
    secretRef:           
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secret-vars