apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-loki
  namespace: flux-system
spec:
  interval: 1h
  path: ./cluster/apps/monitoring/loki/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system