apiVersion: v1
kind: Namespace
metadata:
  name:  monitoring
---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana/grafana
      version: '7.0.3'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 1m
  values:
    replicaCount: 1