apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/part-of: networking
    app.kubernetes.io/component: ingress-controller
spec:
  destination:
    namespace: traefik-system
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://traefik.github.io/charts
    targetRevision: 37.1.2
    chart: traefik
  sources: []
  project: networking
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true