apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi
  namespace: infrastructure
spec:
  interval: 30m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.40.0
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullReconciliationIntervalMs: 120000
    operationTimeoutMs: 300000
    kubernetesServiceDnsDomain: cluster.local
    featureGates: "+UseKRaft,+UnidirectionalTopicOperator"
    tmpDirSizeLimit: 1Mi
    dashboards:
      enabled: false
    resources:
      requests:
        memory: 384Mi
        cpu: 200m
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 30
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 30