apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-lldap
  namespace: flux-system
spec:
  interval: 1h
  path: ./cluster/apps/security/lldap/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system