apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-external-dns
  namespace: flux-system
spec:
  interval: 1h
  path: ./cluster/apps/networking/external-dns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system