apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: tool
spec:
  interval: 1h
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.36
      sourceRef:
        kind: HelmRepository
        name: weaveworks
        namespace: flux-system
  values:
    adminUser:
      create: true
      createSecret: false
      username: admin
    ingress:
      enabled: true
      className: traefik
      annotations:
        hajimari.io/icon: mdi:sawtooth-wave
        hajimari.io/enable: "true"
        hajimari.io/appName: "Weave GitOps"
        hajimari.io/group: Tool
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host gitops.${SECRET_LOCAL_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: gitops-ingress-certs
    networkPolicy:
      create: false