apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: tool
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:RVcqgQ8=,iv:+GNZRY44DeDYvkmi7F85Vt+YhZcqF95W7KRz1BWfx8E=,tag:GnMYdF8D+emXAAK3k20RLg==,type:str]
    password: ENC[AES256_GCM,data:87hqZNNWtdOAmPKkMjs3dPA/KKLxjXiVSvM7rf23e8OOVywz5PYOQyOg6YE0VUeEBNdXKtz+B5HM0j6b,iv:D+VUttzZJCdwC1DfdWM9WPw8N+s0fxjk8qXM+Aih6cY=,tag:ZfRENB54IPUzfAHDEER7bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNkl3UXJyaEo0V3k1NFBm
            bGpEWXZ2enp6U3d2cko5TndtUjVPUElkTmc4CkhjK000eFZzV0dSc3JXazgrSlZu
            dVNYYXk3WVgrTWJvVXFRN3JadjJzbjQKLS0tIENKSU04SjVjV2lKSklTNVJ1SS9k
            QVlRQWpiZWUrU1UwTTZEL3UzcEJEd00KfRjFWK09EIUeh8SdP+SHBGXFUD7z8x/9
            yrxytg1VFxVNYhzTjuKG+z4jOMEnp5LNU50zq2NUmAYdvA87Oi6wIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T17:17:56Z"
    mac: ENC[AES256_GCM,data:lOKKsmbS4kBrk+RFzJx0ujt4LXvdXjVY1XRNleXsgD26nqLnSecSg1/KJSzCHBSIz/BZqeepO9LqJ8yxGVeaR4ukloVUAPZi4qVxNkOXgbKhfDL2vfGsXy77Hp/0upnRUOSBw5asXiZJEvOO29nzGkO0kGO0taNKmC/L7TL0UxE=,iv:eD+S8WxleZ9bpO9JX5auA5ID6U7Fn0jucncPMkYnKS0=,tag:T5RdaxUlHX1emZrYRa0vvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
