apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: tool
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:tLuEcOE=,iv:DcFmDmtTU6Q0oaUVZ7EJ673FwtIzIUWy3uX+/UmO7mw=,tag:WIx0VYW/GaFb71mNkSA3ng==,type:str]
    password: ENC[AES256_GCM,data:WJSjsJW79XcneGtZBKV4KVcvwtg5E2qxWR7piior04FJowDj4uE5AtNyMm81KOSudNTElXs9XdSZhS/B,iv:E60CVxOj/CQ5RZetsYRwgur02oOxNbM05bkfnTxdrzY=,tag:eoBKRUnalF67OyLMSmcnuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcHA2eFhoa0dXSDRVR2dm
            OWpzWkZ2eFhZQnRjaU1tdzhYWUFxL3h6QWljCjR5MlN4bWxla1N3dG1rb0IwOFQ5
            c3JFS3M2WVZyUjdCWE56ei9lRWY0N1UKLS0tIGxjYTV4cXhaQi9KQTdMMnlSOTR0
            N0gyNW84T2EvblArRFZhcUdPK3NKTEkKDGim1mfG/ZCCpjRmr7H3JsqBrZdJGxUy
            heB+8jVcPvYDBtdxuP1vauVMXoWHypZ0hH9keQu7FNlh9/W0Grd5LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T14:03:54Z"
    mac: ENC[AES256_GCM,data:EsoGFwz9RzpBi/P9nvFj+D1Y5+Sv15IA3MJIEuaVBxrCdxobxdPHZhomJs5EIkXAdoAzWMs5PlErVGPCLilc9qucc1z2mgFRyh27p7l54ul+KJ9U9IhmVdTFRf6r+EThQ70HuGgio3mFZhJ/8r1F5YnZ4iq8dxSWgfdBHlrZbMk=,iv:aa7vchcohv2cAcmyVSF+L3mVP+SxJxkYz3ElCUSeTA4=,tag:IdSXdhnXxNLc702DMh7lLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
