apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: tool
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:jyljXlA=,iv:Liu+kBxChwG2/3TC9snfMqkao4ri0wZHICEE+KVm3aQ=,tag:P0z3/hfOPEXD56LD8oYuHg==,type:str]
    password: ENC[AES256_GCM,data:JC5OZ2+7gWFIj171sMn5Rq/hgpWrhiwSmw8/OdB0fuCEBYdVW/GRUXJ6wWR5AUWw6grENCsiM8tgfRGn,iv:/+0EEtK1iEOo70sNAe+uTFd4f1t3wMkuGrG6Ltb+FTQ=,tag:CVA8q/GBYkxXZSySCpaz1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOWdmR0UwRWN0SmFwb0Zs
            YU5zR2pSNkk3Q0huMTlJd3VsN3k0NFZEV1FjCkVFdERqRE5reUduZVFSODUrWDBN
            NE9seERVNTNqNkZYWUhHbThnaDFIRmcKLS0tICtVS0RzZlM4Ni93NmpDZEQ1L21i
            ZndXempnbTFBNkh0MTVmcW91Y1Z4V3cKjjqdU2lMaMCHihYXOENtgDjKciZVvJsc
            Ce5D50E5IF0HWXTwuUWxMjKwKAwWzbLCJ1ckmFZMrdO0gvjRlQISgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T16:44:54Z"
    mac: ENC[AES256_GCM,data:pavMVQX93qFFy2HB6d4umCR2wAZNfblKqlwmCwrUq3X80JdLjjZHAQMxS8YRbfRq6PAsdZ7QMuVZ4Bre9MQaEvxBjdjB2X2bi6FdZ/uKFalbyEq17A3sLjNiydpzTs0KOxk7dk+QRtBl/MLTrd7L7IMqRhlZjtfb+KDGTKWnXlg=,iv:Xdi0IF2q+e2HZucfyHEyBy61rXbTO/Xhd2vbBbFZXmw=,tag:L1X+oyhn46nYOHRMhVMCag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
