apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: tool
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:I1kxohI=,iv:qHBcXoSfS25QILPruMvZT/VYgDxJwDkVBH/FeE3cz1o=,tag:Wy+Ot01u9Gy4G0CExtv0eQ==,type:str]
    password: ENC[AES256_GCM,data:RmJuZhmoYokxdQP3A/qDcuMw3heew2JcCf16aoO4enfSMm4ef1zyggXqfWRr1D/++AlQ3boUv81+pv2D,iv:IdsZc37atTFbDjxHKamdtloB63/pReiMkLf40zwOaAg=,tag:vhAsiBuvRt5bbysGDpdWiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIKzVTVlB5WU1EYkNZMU9q
            L1k2d3ZaTkR2dHFEWm5JOGFKaG13T2YzZUhZCkVKSWp0ZGZYcmN1QnBGblBKd0hO
            NU56RmVVWHRpTFQrM0EvcHBYb2ZKUXcKLS0tIHR5ZzExQ3JRS3hPazlmd1NlSXRy
            aCtOZFAvTkNqRlJUbno3eVg0WTRJNnMKXf819+9X59YhXUIKv22iCok1m1NgiSDv
            TYtL14KLEXxZ9BRp7RmErSc39o+1hnAZR5MyPlhOP/KYKSqBCsT3ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T16:39:09Z"
    mac: ENC[AES256_GCM,data:Tj7uRTiId+IIYGjMqzGCNGea+2tbhkDKKf1Lb0QC9WayOmadhpysDquUuDHQUqJdpyvNKwJxOZRum5BCGZLxHtuKHTFU1EsHQuMA3lvMCdz87wohVfOJLPavZgcRomOoJokFMi1iuEh3iaqjIzXQpOBAJYxUrA6hW52nz8tMq5I=,iv:/+sdRQCeCH3sf8iEP5IXAcHzxfhy7N4RCg7tP97ILxg=,tag:ybA7UJ8JV+T6ZfuX+NRybg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
