apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: tool
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:zmH/gC0=,iv:q1f6QEDbD995YyZDF1bl2gLVSwsmfvtwl33vWGtrXFs=,tag:Nd27S+YKfYI9rtYlzQP27g==,type:str]
    password: ENC[AES256_GCM,data:mm5W/EUip8ZdKsfB/Jh11bKnkIfWSIDYJk3HkiCNQLNhQRtq2TRJhXwl1Ou78RGM7FKykada0t5wEXa7,iv:1gW/ArBSizCgkIdmpAlZJgK4s/0zqWVm+miUOxmT59I=,tag:76uXEaIkg8vCoaMJVJCT5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWmhGbXdTaTA2OXIyRERM
            NXJoSWdEOUFpbTZIQUMrRFk5N2VhVEVhQXdjCnVBa0lDd2tkdUdGQ1ZES3cvSFVu
            Tm11SW1EMEp4TUllRHlJcHd6QUI0VWMKLS0tIHFJVU51dGhYVlowSkdPVjYySmU3
            QUxIWjZpUlN1OUkyTHJocDFVUkJRcWMKFUcpdUVEMyiktGjalnM0Da49PpPRuXwU
            7P2bAsxPGY2PW9Ot2PrXww3c3/L3WFgwuQZS/nvIZLriKGQdwiYPrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T17:22:06Z"
    mac: ENC[AES256_GCM,data:BsI7HypZCv2nDcxCL7W4ywcWbw6Y4OerUBXy9Zd9TSt4maNA1eBIKqsIT6zDa/UEo/r1vG5jmlfZyejMk6p9QJ2bXwwvmlb/Y4YKLRXkKReKkBVPGQKFrzTGeDcoSYdQHNHnVquBakLJ/kwAblog3xHsCJnnmiT4z4Fp+4NoVrA=,iv:zhX9jKP0RBYY6UYkAkc4SEtWVrFBdRC6mn5d7ZhuDXo=,tag:vCs5ozJGCGmMN5JNniEYcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
