apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
spec:
  project: guestbook
  requestedFreight: []
  subscriptions:
    - warehouse: guestbook-images
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/thaddeuscleo/cleoverse-gitops.git
        writeBranch: main
        path: workloads/applications/guestbook/overlays/dev
        kustomize:
          images:
            - name: gcr.io/heptio-images/guestbook-ui
              useArtifactTag: true
    argoCDAppUpdates:
      - appName: guestbook-dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
spec:
  project: guestbook
  requestedFreight: []
  subscriptions:
    - upstreamStages:
        - dev
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/thaddeuscleo/cleoverse-gitops.git
        writeBranch: main
        path: workloads/applications/guestbook/overlays/staging
        kustomize:
          images:
            - name: gcr.io/heptio-images/guestbook-ui
              useUpstreamImage: true
    argoCDAppUpdates:
      - appName: guestbook-staging
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
spec:
  project: guestbook
  requestedFreight: []
  subscriptions:
    - upstreamStages:
        - staging
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/thaddeuscleo/cleoverse-gitops.git
        writeBranch: main
        path: workloads/applications/guestbook/overlays/prod
        kustomize:
          images:
            - name: gcr.io/heptio-images/guestbook-ui
              useUpstreamImage: true
    argoCDAppUpdates:
      - appName: guestbook-prod
  # Optional: require manual approval
  manualPromotion: true
