apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # - ./coder/ks.yaml
  # - ./coder-db/ks.yaml
  - ./hajimari/ks.yaml
  - ./weaveworks-gitops/ks.yaml
  - ./outline/ks.yaml