apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-release
  namespace: argocd
spec:
  project: utilities
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  source:
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: 1.8.4-rc.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true