apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-redpanda
  namespace: flux-system
spec:
  interval: 1h
  path: ./cluster/apps/infrastructure/redpanda/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
