apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zitadel
  namespace: security
spec:
  interval: 1h
  chart:
    spec:
      chart: zitadel
      version: '7.3.2'
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
    zitadel:
      masterkey: ${SECRET_ZITADEL_MASTERKEY}
      configmapConfig:
        ExternalSecure: false
        TLS:
          Enabled: false
      secretConfig:
        Database:
          cockroach:
            Host: crdb-public.security.svc.cluster.local
            User:
              Password: ${SECRET_ZITADEL_CRDB_USER_PASSWORD}