apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app-rollout
spec:
  replicas: 10
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: argoproj/rollouts-demo:yellow
  strategy:
    canary:
      steps:
        - setWeight: 1
        - pause: { duration: 1m }
        - setWeight: 10
        - pause: { duration: 1m }
        - setWeight: 30
        - pause: { duration: 2m }
        - setWeight: 60
        - pause: { duration: 2m }
        - setWeight: 100
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: rollout-bluegreen-active
# spec:
#   selector:
#     app: nginx
#   ports:
#     - name: web
#       protocol: TCP
#       port: 80

# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: rollout-bluegreen-preview
# spec:
#   selector:
#     app: nginx
#   ports:
#     - name: web
#       protocol: TCP
#       port: 80