apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app-rollout
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.24
  strategy:
    blueGreen:
      previewService: rollout-bluegreen-preview
      activeService: rollout-bluegreen-active
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-active
spec:
  selector:
    app: nginx-deployment
  ports:
    - name: web
      protocol: TCP
      port: 80

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-preview
spec:
  selector:
    app: nginx-deployment
  ports:
    - name: web
      protocol: TCP
      port: 80