apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app-rollout
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.24
  strategy:
    canary:
      steps:
        - setWeight: 20
          pause: {}
        - setWeight: 40
        - pause:
          duration: 1m
        - setWeight: 60
        - pause:
          duration: 1m
        - setWeight: 80
        - pause:
          duration: 1m