apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
  strategy:
    blueGreen:
      previewService: rollout-bluegreen-preview
      activeService: rollout-bluegreen-active
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-active
spec:
  selector:
    app: nginx
  ports:
    - name: web
      protocol: TCP
      port: 80

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-preview
spec:
  selector:
    app: nginx
  ports:
    - name: web
      protocol: TCP
      port: 80