apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      version: 2.3.0
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
      interval: 5m  
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: -1
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/fallenbagel/jellyseerr
              tag: 1.7.0
            env:
              LOG_LEVEL: "info"
              PORT: 8080
            resources:
              requests:
                memory: 443M
              limits:
                memory: 536M
    service:
      main:
        ports:
          http:
            port: 8080 
    ingress:
      main:
        enabled: true
        className: "traefik"
        annotations:
          hajimari.io/enable: true
          hajimari.io/appName: "Jellyseer"
          hajimari.io/icon: "simple-icons:wpexplorer"
          hajimari.io/group: "Media"
        hosts:
          - host: jellyseer.${SECRET_LOCAL_DOMAIN}
            paths:
            - path: "/"
              service:
                name: main
                port: http
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: "longhorn"
        globalMounts:
          - path: "/app/config"