apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyseer
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyseer
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: qjoly-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    common:
      persistence:
        volumes:
          - name: "data"
            storageClassName: "longhorn"
            size: 1Gi
            containerMount: "/app/config"
      variables:
        nonSecret:
          TZ: Asia/Jakarta
      ingress:
        enabled: true
        hostname: jellyseer.cleoverse.home
        tls:
          enabled: false
        ingressClassName: "traefik"
        