---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secrets
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgCPw9mPqztQY1V7FEMY1SbL//9StYbqCKY+ulgXsGP93eRM5UC+8BzyW4F2a+Zbex7/N4lWx2fdcowU9XsaXhY3a5Jbp3m9FGpWt4UWzuVqLYi1lP0SGxQoAosDnN63I/MCXEJp8h0vBLfEPmkrea9wsIadfrImBwX0LG5LSFrKz9xhHo+oZu6f7vBclU6fL+cbebsI1WTicynMUUJt1ld73Pob+iidw7AbDQTXZOATNLFIoBHJLDFy6OUZkD6LovrNeqEDW2o8oFOCgxQAEpndHLi/zhDlPuAvaxOfqF8zfS4vzBS1e6mpACFBtc5Khs9jK4rC+3SxcOLQcsinvSOVV6mmqVN9hOI6zTxWr+iBley8PMmWMPyxRJaj8v40kLJ2GT+DLgxmSDtzr86nlCvpBtJ35SWVn4alMgYY9znxJ/2Vxaztch2tTSJHMVkES0iuyJLvm+FCXBez6ZnGUiRCIgWZM4/2wh8HNvzBGFp/kpyjJZGBcCkSgEi8VuFCA6cGQ/uVve59DiVj0kgVttd3lZc62lrOf8MOiuWHKq0KWV9CFdS3JDNzTlzxIpXJ3ias8GBtUEb0z11DNZLZr+eVuvORMEWScFy0ayXCqUCgP/J+sG4UcRG1nPNNZFd4ak5fEUWiHwnC+7PtFbSjBDgP646vx2Nx1k6Lh4T/8xOnN/XLQFKd8HMFNWVtXxc3uX+EWu+LJsHcLzWtQ0kZEBbzKt/mxePjOWhk8P6oUfgw8t3UIKM9OFBK
  template:
    metadata:
      name: cloudflare-secrets
      namespace: cert-manager
