
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-release
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: utilities
    app.kubernetes.io/component: cluster-utilities
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: oci://quay.io/jetstack/charts/cert-manager
    targetRevision: 1.19.0
  project: utilities
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true