apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-release
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: utilities
    app.kubernetes.io/component: cluster-utilities
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.19.0
    chart: cert-manager
    helm:
      valuesObject:
        crds:
          enabled: true
  project: utilities
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true