apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: security
type: Opaque
stringData:
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:Hk/Bs1ApYrBN2ME1YGh57IhOSNoCaociqQvXlnMk60GbZbh6UAvtrp7YegFXB84bSHIHeXwnaNRnfOnIwAFSZ6IUhXRAjNhebzlKMHh8CqiGKgMF9C7hlkoVkCFo6sznq/4KcIaKExRqRd14YCxCCn3A6gqHlXg4Z++Ux3mUlMGWUty3aUD/WNyHMtRt4UDs,iv:8K6H4VgFSqyCY7z/U5zqatCm40RHv/ydSvOuV9XyEtM=,tag:59GbqKemDVqleqUYQOx2xQ==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:7qXUBKa9wgMQM9/0WpYJIeWJjzw=,iv:MS1EIsKGjght4GYeXTAOn9ZDYr80UfmvH318i6HT7DA=,tag:RAGeu/5tWKQFMPRTattgdw==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:gZM1E3d1yIkPkfZadvrtbamF1rMalQ==,iv:qI8MNmMEqW237As/dbsRRpoHWkXApXIg6WEKxfWrIDE=,tag:rzEPuvrTCFzv+h2m6DBT7A==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:wmFpbUCBOYV24mw=,iv:gylvsaQPw2OYPDhjJRiX4eb8mCvtFwqbB+rpvgXiilo=,tag:j9yrkGgleOGfJNaOuXxW3A==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:lbotvwi9vkUHhI5RuDMK9Ig407E=,iv:dRoYlWg82PW61lpYPYqDu3jUnzLNE5ijHW8929L05xM=,tag:ma9CKP/k2DfoLgam+Dumpg==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:jc/hyMTpy9IiDEt4nurKsDoQRXuAsTkaQb954J6CZqSlBwlWmgM=,iv:ck43Uyyn9fQ+PfjMti2HUgBVX8aZY+CUSPpekLhzZqM=,tag:KpObQiqveHDzCHiDTxwxIQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:I21hJ7Y=,iv:mCzWPQl9whj7eZi/Gs3ykxeKXYMzWuzviZukx5ZIL+g=,tag:6AovXiA77JPF5vAfqa0EkA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:LqVo9BCn2KVsFsevFd6d5PE+HWlmtpUuK4YBMZAL35ZlxZsCxTBqnGP/QeIzBvJwsQ==,iv:miN0c+LCKVq3/csw327Bwo4K+r6kUmDJBrt/+RRgD+Q=,tag:KU2I0Ct/tkm2Rp+hR8E0sw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:QE3G+VhwyDTHAaV/iPSc5ZcBbH/Ewgyn3Qbnf1E3FPRPLOdH3Zs=,iv:vsAVUvajflJ9F+QaSSU939f38MdwUS97McrVFNY3ShM=,tag:lP/pzyzxbEiSzMWvv7a0cw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:5wbFVVBB1zao8ZYd9byCDwljzOaqjdUX4kg6fbywHO2mHgGnIl4=,iv:oSiULLQgdGxacW2ivhGOK09yxePYCFOQmCfOKRxiyU4=,tag:EKHuZt89B6ai3jeFJgKGZQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Dbu3xVOxPyDYb1ocf25ib/NtlShCsYmMAqph,iv:9htjnJtbMBWfpp/ysSfilKr0LHF460nck7R0GuMlTs0=,tag:sABA/JYYffiPlvmiIsQYiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcXpBUExxRGQvNUNOczFH
            RzRBdTQzMXUxUTl2T3hGRW0wQlE0NlRPaEUwCkt2dFM0OUxqb3NIeHREVTcwT0Nv
            cklnSHZpT0JOYlJKQ3FBS0JqSHRZOTQKLS0tIGU1MzJXb21aTS9hb2lOT25tYXd2
            WlA3VVZ1bEpweCtUNTFSZFJGU2JhSXMKiliZZWn+l1VFgUDQCk5V5k7EO42meN3S
            FranhVuEL01C2PWU4jQokbFzfKOgoFxvk32/Q1ANLS1yJRcNl3MYjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T17:33:47Z"
    mac: ENC[AES256_GCM,data:HhnM0wCrqylh/UAIo4PGtKpoXfmBS/2U5Tbbvi2TjSHzr9cZKR+t2UMKKZSqJiAv1ODHgoIjLn6ojTOGj08qgS9/iw0rcmurXzBfziNF8BCLFjz88D6KlWgEdeHMfvG7nKu7sWc2MLRCXEhAVP5m8GRSnYj0flXPh8ZqUO1oOV0=,iv:padmJugg+7TXpfEpRIezKwVW91Af6labLAMBwmJHzdo=,tag:qpHbcE1iTPgZA23gMcdrGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
