apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: security
type: Opaque
stringData:
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:/yIjDawVTJ0YRvdib47DloC+IsAat/sjomoAgwh+GBCV37AHTKdZr8Ki27ivhUVwswqNTK8tbo4o2TJKlfPaxeJDHjj4MrqgNNED3VtpiJ2gJn8+NwhhquyM490xWN6Iq8kc8oJkH53iOo6/bTqoo1z9tkzZ5YAHF7PVJ6EpwTGwSUYd2fstAFWTvzwibPZr,iv:3AbzvckjNrNbkvaFndhLmP1hChY5nztu7H/8PTiOPac=,tag:2hRzFCL2oDKtY8+nOGRS+Q==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:NF6KzSRdYEc/0jR6BZMYB/amjY4=,iv:LT2sPmAYBAFc3YNGvdKpGSmz5yfsZv7AZg/KhQPMCzY=,tag:LF33+Agn9rippRrWMC69WQ==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:lQhOFqUY4DwSyi1aFJqiO3HmmduCoA==,iv:PJsjDk+ne+eTXbNLQki6N5R+SIhHeeHtF7mjLoDHG2c=,tag:8OUMom/qo1/3fNanpAkh8g==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:dVm7oNnUsawCwps=,iv:wdyriNfBDtg04FrASJySjPAkwqp1myLEJMTXZbgGL+c=,tag:4r+NUYR8Syza9s3U7gKFJg==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:d5Wbw5y0h0Q2o7R//elM+MvKTys=,iv:sdlH7iR0EhJsbzeFT9btAUFUglvEnP7ur2vxfZ7f06M=,tag:ZB00xFrGuo7YmeSlQvkjnQ==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:YQJxYFtKPdziPe1wJ6GKJ/XvptM3quKjJKu8m9iVem/UKa3bD6g=,iv:+Pv/4/Ruzl0K0NJZkJpWNxX88gLyUCxYC5gy0lWZwT0=,tag:gkfiBtVv+hZxM81JoQf6Vw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:tfx7SLw=,iv:sTlap1TBdlHgH1t8qi2vo8THrYCAYo0Z1p7mTQuAX0w=,tag:84cy/2AYousUu1/BAVX6Dw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:T7UWPUKd0R84PPq6eT+OioNkCntIxxFon4qT4JBDfSZdS18fTtxKqZE+gj5GY3CMdA==,iv:tZkvvS12ywbIq410fqlm//Fk0EglQ7NWZG/TMamJtg8=,tag:pAPsrk4LYc5gX1F1Or5QVg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:9JKyW1JiIi/OD0VNwA5rRKkE1JdY/hAtGM3XA5Sm5TeCAj8L6dc=,iv:oz1bFVC5gHNJT4DovjABJ5PeIVIoycRiGKy+XGoF/do=,tag:S0/QLXRqaBGO/xLD9wRa7w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:2TZA5MF9T7j1ANu0gsRC0TyxLSsTeiGzxv8xczQerPjApx50x/k=,iv:5nCemPSeRRjS0By+CMz6i0NloyVeIq3lUKgd9vV4Azk=,tag:JIfGd0rTgE0pQCMjhQsgSg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:esG6WVwlVsxTTXOIMnelRCpHqDpfXkhaFZ5R,iv:fjleSWOqagUVdQZrgF3eDK0+zZ7QMgOWNOEGHjLAkl8=,tag:DIH54U97AOcmcGv3UW5UOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a1dkYjlYYVhMcDFIMFZo
            d3NzVlpUeFJSaml6ZkN2MGlPLzVVMWNCS0hzCmE5KzZieS9RMmVwZ1JXdm9RRDFk
            cDNDMVFpbWl2ZWorcHpsV0NmN21SREUKLS0tIFh6ZGxLaTlOdGd0MnJtRlVxSkxI
            REVVQlErazlNeld5U1BTL09NNzdoaWsKwYiJJo1UslIIpbUkD7U580Hw1w2xgQjz
            qw73ZtTOWrvk5JnSkVO0XNmq+6hUq4SLmPKaTY5FLCEUjXNP8lYprA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T14:03:54Z"
    mac: ENC[AES256_GCM,data:kMBelDfgH4M6WngsyJk1nSTBKSA791M8z+am5cPDRJmPzGf8W2SYr2Xo94eyOZAFPp1D9CAWCZ3RlT38ogNHCfygO0iQKS5BznySK2AiXvHLBDVsEyaumGFqeroum+aiY7LOzU6QeamsSejNJPUm2bZSx/Fh0YYo9aPgF76wF4o=,iv:Nv/xuICsXlHO/onvfwbDh8hFGIpkCQXUfqsTYvCq5HY=,tag:+g80dh/wPHDgODVKIcBwOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
