apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: security
type: Opaque
stringData:
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:RfOo4jUFt52EWO2i6Zu72gpvpfhlW8KlhnaOoP8RnFXTP6wKf5KSZ0mlQDSCozZtTAZ3GGFZT2ypYdzOVEQq83DwrrzdOMiGgK4WiBMWScb7KYwr7PPxR3ZEYTnbS+P3DoleGUDmVGTzMqZ5XVf6cMRPpyrU+5WDxHuaDMRvWH1JJNTnlK4ifQ6AcZh795fI,iv:MVmQvp4s470/SpulyarXHEQXQ734V9hgHROy4HayXtY=,tag:3zEOoNbWw/VW5FUOT6AkUg==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:eGJfMO9Gta2Kp+ojn67G45HA0BI=,iv:gYFDCjLkfdDcndKcT+P48bvWnQvx6+Xd9YxxqPvnPro=,tag:+qCgcHO7yMEHMW3yxmuVmg==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:GV2nso7PaJzX9dY5fYHDLsF2ShHpQA==,iv:WBSFmGAzn4YJiHkxX56mrz5KY8cFg3+dj8r6oDW9Prc=,tag:k82n9iErnhUARKvZQ5WS7w==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:rQ2UX0bdE3bU6Bo=,iv:nrD4Ai5SnoO2azYxGF74ylbXUei8RtAOQerw9VsY6vg=,tag:K6/c90sbqmUxP08oU6+t3g==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:mX4MvEZjuWP65zb8x03XkTMPJis=,iv:GKGaNLJYFytBH8AhsDFRSCjLIcLm5frgiKfbqDQgODs=,tag:Et0NNQhmhFNhj7Id0o0QWA==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:T/JHWtDb22uftExCrmgGJQNCuTdxj5mAQFL1D72RLjaNXdG4B+I=,iv:E0QYz/OMxdt5SK/ieuyYnY2fuIIjEbeEIema0myYif0=,tag:8RFhzv4icCNJGs886dZkfw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:oqHtiPM=,iv:FvSNBTZGd2oQGEutGj3yZnh4pkyrGfCiAc9NERx8hJo=,tag:2TQkpNtATzi82n/BaQDI1w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:w9EspCMA+d5CbmWH0T2FCnd7jYEbt3L1tIQati1eRRUgqBW3X0vKflbhaZdgGLf61A==,iv:gbdddY3L6nsS1bW/lpLok94QqIzVdgShdWj29l9eBGo=,tag:hhN27YU/vvVN56ILmcL8CA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:hiOpNThQ/SyTpPVH9aluLX4yN5VE8238jQunpR6ISYShBoOXG/k=,iv:TGWS9GgWr7DxWtdbxhBCmQN5uc/c4uRWI1YUP4rq//Y=,tag:MWnHkRhp+mXuf/57ro3jQQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:SHLoihBgdBc2dveSQ4x5mAwzz3JOI+g3rTwL6G1NRsuTS0tWiLg=,iv:CXZjLsANVkmPUCzIyteXN+WF2z1NM30NYMzJOGASZ5E=,tag:pJ3NnQYl1ZEi8ChnVZINpA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:xGE4Fy+riKgT9gDWQCDKkJwD9xb4bGtGaL1Z,iv:oGGCNHc+gy6qPoOrL0kgf98JdgxQrEKwnzUVs4+rc4Q=,tag:If5ymPSJkQq4Z6Jy+ZiDTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdDBQa3VwZUM3U25PaURF
            VlhFU1dWVkVEeC9kS3AyZEVMNElaTDBraXd3CjUvTW0wSnBVT0xqcy9VSXNJdXRJ
            azh2ek1IZzMxSmV3VXU2ZTkzTUdUTG8KLS0tIDRsSXplZzFLajE1bzc5RitzaGE2
            ZzZId25FQnNyWmdZL0FSbGl6Q1g5QnMKdRyCPVPiPmBS/MW2T0U/CAoXq+Ej4LXR
            olSXeaMexQkf5yWrKpWuARKtgeyt6RrXCUwSU3Pv52WXsD+xU5CVLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T17:13:13Z"
    mac: ENC[AES256_GCM,data:xSt7fjYTLP+/xbbaORciiZ58jglZCDKLf4APO8UCxbGdf+C23IBPV6aF/SrRpd/IPO6eGyIXgoLQFiuBj9d/XfrhDekTsIf0PUmIaMzAbBKbisHz11wO3Oae5VnA9RUbU5I6GKpeuHNeL+adXfuwA912L1ZADBc0liCbXm7NDr0=,iv:daktZFrgnnKV5BXPIYIxw1sJrips09Pv0u1lrxNapkA=,tag:MUeVEuLBwQPqBJeB5eBbBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
