apiVersion: v1
kind: Service
metadata:
  name: lldap-external-svc
  namespace: security
spec:
  type: LoadBalancer
  selector:                                                                                                                                                                                       │
    app: lldap
  ports:
    - name: ldap                                                                                                                                                                                    │
      port: 389                                                                                                                                                                                     │
      protocol: TCP                                                                                                                                                                                 │
      targetPort: 389