apiVersion: v1
kind: Service
metadata:
  name: lldap-external-svc
  namespace: security
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: lldap
    app.kubernetes.io/name: lldap
  ports:
    - name: ldap
      port: 3890
      protocol: TCP
      targetPort: 389
