apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:jv5Hj1zTwKfuvpoJtnMWS/5m,iv:WXGuJ+6ELEH/xcGQwEAh6HIEv5Kdtwo91wasUubYLDI=,tag:jxQbAOw1qjO8l0e779CMyQ==,type:str]
    SECRET_MEDIA_STACK_IP_ADDRESS: ENC[AES256_GCM,data:EpXPdc3cKedjwSNOzA==,iv:Oh69rOBzISWjZor4ryFrHsVmpiuiW8Q+6/XOBr7I3xM=,tag:Q9znGtFfCjS2uYVYjg0R2Q==,type:str]
    SECRET_CODER_DB_USERNAME: ENC[AES256_GCM,data:mNa2hEQ=,iv:/QkFgzwt9ypnJFdK0BTNBxSdrTx9693Dlp3zMYwiKnI=,tag:beJX6jFgfYi+VyQZsp6/jw==,type:str]
    SECRET_CODER_DB_PASSWORD: ENC[AES256_GCM,data:OSevGZs=,iv:7LPW12cfBESdTViAerqUdj8+Rvd5jmyefcSAETPiuRg=,tag:6DLJWOhdebR9VUc8hB3+tA==,type:str]
    SECRET_CODER_DB_DATABASE: ENC[AES256_GCM,data:xTETVAU=,iv:wtmGCCMWsfAnRkefiwxZuN7yfiUTRyvtGPTruobemg0=,tag:WB/vog/GzXuapHHPsDoNww==,type:str]
    SECRET_CODER_DB_URL: ENC[AES256_GCM,data:/qOhrb4n1sSd9dDvPG830BX2IXm3hIktmKeWZXwBzEgQ9CZvrPMQPTuluwCoXa/3PiX2IQUL02uJBCE529FX/+WzR0GsAmiKd19bDrTu8eWfDF0993jqz1ut+l4=,iv:iUDZOkvbW6p6vNnB/7q0CyhOh488tv9pR3heDfJ+c/c=,tag:xe0S+rai2QtRunOoHzLpVA==,type:str]
    SECRET_ZITADEL_MASTERKEY: ENC[AES256_GCM,data:KbzkWQY68GzEQAImh2rfd9qGiW9z+k59igBorg4TFMY=,iv:T4+1jwh8t0nYOJgsXhs6TfVq/j2H4Lr7V1PRCay8HIQ=,tag:pgp/1I27zAJaPc4mUjzzCg==,type:str]
    SECRET_ZITADEL_CRDB_USER_PASSWORD: ENC[AES256_GCM,data:mVNlPcNRYYDijiDFuPJzopZI1mjqynSfl90=,iv:8qgdrICJ3PoE1e1FlwtxzCtcG1dYSybM6VslLSNkrKE=,tag:DfuMcF9562DykVcw26JTMQ==,type:str]
    SECRET_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:hwiQwnF+cIJZXsL3ThT5ne07MkwFZLuk9Qp9EAlN7lXXjeFH+FRkrw==,iv:LiXrSlLdMxyfpIxJeAvQYW9PDHIWbdmDa8OCpyy1+14=,tag:7RU209kTgx0FkK2EMX7INw==,type:str]
    SECRET_CLOUDFLARE_API_EMAIL: ENC[AES256_GCM,data:zYOFJ4GU6HKI0Ww6Hp98uyGtypbpsQ==,iv:FjhO1KfQ7blGASya4UP6s4ujvB2El/07549o7OArgr4=,tag:mio8V09JbeZK0XXrPA38UQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZm1aRGQ1WFA0Zi90SlVj
            d3dqYlpwOGJzVnRYT3E1Y0hvWmlSYTh2Q0VZCmplOHFBWUlBNFpjLzNSOEV2L2Nj
            Rm5VWnlXczN1WDg2bDJSVnVMVzczYmsKLS0tIDE3RTFKQ2VET2VUaHNzN2hQVllv
            T1RZR2RGOVNFRVJQK0RrbUtQckFOak0Km6Hp6MwHhYYnP2ZPARKLLXJI+eLF8viV
            xOriDJ3uMsE8pT+anqDZVUAziwvKBelPe1HWuKqpqp/tXqFdivYVJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T17:03:04Z"
    mac: ENC[AES256_GCM,data:LPpTSVBDRlRIDxnPOkm+ivXj/xlqKbjXK+Geombzk4u2GAemW1BlBXjEgRfOwBbbD11jq7jRY018H45dLM9ATFFEzQ4UaoM9alOqHSrUFGu7W0ZWJb848KccyeX2dbxK75iu8tm+a3ULD5CNwzGa4D4CDTOeR8cEZmAGwv/6xQg=,iv:kz01qfC3q7GAqKC245zYsmiXS/hiXWB+YE2d8617/mQ=,tag:zawocuEu3NwOjje464bRJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
