apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_MAIN_DOMAIN: ENC[AES256_GCM,data:D90/e09+nKQr6c8CTg==,iv:wfP0auzyNSxCGuY9o4VICGtoQ7FiiQ66/bg2z2hy2CA=,tag:sXGPKNy8m12w6pcClgPCMg==,type:str]
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:hPiho4aJetX73+X3nfxf4DvM,iv:R6tft7ZFwUz0x5W1GLSRSTMFlSuGI73YgaFO+fk3pRM=,tag:IpxDDN+ItCjXvFBQQ2eAig==,type:str]
    SECRET_MEDIA_STACK_IP_ADDRESS: ENC[AES256_GCM,data:uYXvUF11U9MmhJtb9w==,iv:EGbOiS1IHutxlkwS3gRvBK3O1ecLJYQT6sFAZcFWVoM=,tag:oQQ4pCCcgzJHdjEH7ZqWKg==,type:str]
    SECRET_CODER_DB_USERNAME: ENC[AES256_GCM,data:vT3Lips=,iv:06I95vcAVptoCSUTrOg+pc1tBkKwk7QICv6dBjAaNH4=,tag:x9koSj7CME1Hhwg7nzF70A==,type:str]
    SECRET_CODER_DB_PASSWORD: ENC[AES256_GCM,data:JIvr6uw=,iv:k4KHg4sq0OIv6Cp6eVfhDQxzAU3tyTsvnB7+42FsgC0=,tag:KbBrvr6c6A1NVV9a8sOkOw==,type:str]
    SECRET_CODER_DB_DATABASE: ENC[AES256_GCM,data:fowFi00=,iv:U8uIYDD+i8WOpEV/Ac0ertc18iIfYkBnXdzPqgdVzuY=,tag:Yh+g8036oITlsE/XXGgvkQ==,type:str]
    SECRET_CODER_DB_URL: ENC[AES256_GCM,data:wMoEfBJbVcnspGcx51AtNVpj1X03d15gSsN3nl2dxCZvs+ixGTZnlLA0ZxGuEYXnkGEgmYWF4nFQZMLt3TlYPIjNzHRPjTG/twNs7hziSTtq3POJJUXvdtNAHGI=,iv:bsrilsYG/jGkE/ecp4z+aXIRH+dp32AhuTo6+wt3vR0=,tag:AyBQIKvLetE/tNZLzgGVRA==,type:str]
    SECRET_ZITADEL_MASTERKEY: ENC[AES256_GCM,data:MAg7LFRiCSWxHcWcLANMhJ+tRtVPwapciai29jJmGr0=,iv:mWRNKEAy7r/PECn+fumEOj/R6LiYmQSKtril5lNtCbw=,tag:0EWbyf69ly53+iDDtFJjhA==,type:str]
    SECRET_ZITADEL_CRDB_USER_PASSWORD: ENC[AES256_GCM,data:nZuZIjdjXrq0Wt+wVXdt/t2duY6+iYYzgow=,iv:BGFk+2OZ6w5WCw+DR0uBm6dhUZejeB5zHzML4ePzdrk=,tag:Zxp8wfqb8sqgt1+dn+zFmA==,type:str]
    SECRET_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:R+ksKKNjFUFY5FKsqhXlIQEQSEihwKNYEHvmbLADp0tZ5w8znQ==,iv:igj8iWq/zZde0HO4Sy9IXi7gzHM7Fz8ticJhP9Ix6ng=,tag:DfXUZ3uUF+Pa1pG0VWmatQ==,type:str]
    SECRET_CLOUDFLARE_API_EMAIL: ENC[AES256_GCM,data:saXtEBvNkZbqqzaq7nR83WGGF2caeg==,iv:dnFXurzquhFQbUQM8GwmD9XRXHzt3d8kaNBzfC6z8GQ=,tag:JlXpU5lFsTyQ+lU2yS5aZQ==,type:str]
    SECRET_POSTGRES_PASSWORD: ENC[AES256_GCM,data:guf6qjpkJZoIKkHq3cFYDL0xJF864RHYSJVzAa/8anf6k/bUQHtX6jyfpuAHSR+xZSaq0DQEj01JosS8gPg/zA==,iv:nffwPyRcr5Ep3DQdJx1mV0pGsHx1D8eD5MuED883q7M=,tag:TySP7dco+gVOstbhB+VsoQ==,type:str]
    SECRET_POSTGRES_LLDAP_USER_USERNAME: ENC[AES256_GCM,data:XnqdSP4=,iv:s/N4grObAMOz44vX0DjNLfe2UtOzBaisq1u08EkPHzY=,tag:DQoRhzufPgF0LTeQa/jg7Q==,type:str]
    SECRET_POSTGRES_LLDAP_USER_PASSWORD: ENC[AES256_GCM,data:i/59vmXsl+RnEHbNzr9l1GgIAVZJ0cRA,iv:a1tymRRqTl9+z43WWMLVPaNnVuI1KKWsmGu+UNzlIfU=,tag:X3O5G3LIbO2zH1UPNpk9AQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeGlZNkV3aDVGVEpKT3U4
            TE9yZmlHUVFFZHNnWXZHbmtVZWJwWnNMQ1dVClFtVG1CMXJnMzhPeUdSejg4TTVE
            NEtmalZvclR6SlVFR0N2UkcwWDB5LzAKLS0tIFl0ZG9nYXpVZGo5WEIzUE4yUGcx
            Q0haYXJoNmI0NVk4MW9mdFViaXJNZlUKNgGQuSZD3pjrkuvf9GN96lUNLZLNs2H4
            GGPqbgQhp+iUQgx6Z6rpXrcFbsyZ7NkyaH4gWoxwHmdKSG1mvdFcEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T14:06:12Z"
    mac: ENC[AES256_GCM,data:0WkJymnvTXpC0CxQwzJsirtpCDYgifm4BVyZ6dGsp0v+ejmmfPrHnyj8M/jrzfGDzBF8b41iNumIdT9cbMl46+UvP6cQ1zOaF9ygenY6d0TDJV25IkrQ7N7P4Iy2lH1cyKVU56TvHbZzFZ0RolKLNUC43dzgLFYsAiE2um9niNY=,iv:hIQyuK9oXBonL5YQXx61fC1eSyjRsndx1js+/HIPeBk=,tag:A/RMCDdBikKvC58L3Srlzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
