apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:VUw6RMwAhqjePQl2Fii+dVRM,iv:i4rox3OreuSIRQA6AOjIjphSLpS0FY1WPKh2bRPJf9A=,tag:IfBdGmM3qJ1QSbAiWTfoLw==,type:str]
    SECRET_MEDIA_STACK_IP_ADDRESS: ENC[AES256_GCM,data:jGA9ZBQbX17O50PfhA==,iv:2+/cmOHjt7it11DimbrwvkpwDUD0HG3OKHx00MYK+3g=,tag:5obgdx1wHe6NTj71J5ehzg==,type:str]
    SECRET_CODER_DB_USERNAME: ENC[AES256_GCM,data:N/7tCm8=,iv:rj+Qrf6qUHAI/Me9OOvnVe5apjf50JvoP9AGfob2OQM=,tag:kd0fQ9mGTrlcJLx9Puzgnw==,type:str]
    SECRET_CODER_DB_PASSWORD: ENC[AES256_GCM,data:zUY5Y5Q=,iv:sV/wg1H6QKOBS+On+YQHwNLTD9AwWxLwV4f/NutsYtQ=,tag:V2cebkEdo5zMVY3sGkafRg==,type:str]
    SECRET_CODER_DB_DATABASE: ENC[AES256_GCM,data:kSylbIA=,iv:ORDympvu0dv11sVZ4nAjDEs2UaiirMfNgcSkBoE/Zfg=,tag:wk6nm4iB+5ew5voRZtkopw==,type:str]
    SECRET_CODER_DB_URL: ENC[AES256_GCM,data:lnuFcU7bUL9USxvfq7xyOLWQJD47qtHdLPlrYQZ8B2CM+Iynhkg0iyXaSHRp9AHAPowfT8+WKFLMkDZptUdAouHa20MxOqLhBU3nR6Ym/7Tm7JmmPvnDd9GkNCw=,iv:AUTYQOfxChl7BIsIv7Fo7Z3pobXhZ4nEr6lDqpJDzvY=,tag:WrhAAi5AvMPnsckCchp1XA==,type:str]
    SECRET_ZITADEL_MASTERKEY: ENC[AES256_GCM,data:WpR4JlCbfr2y7o38pUle5aB9DlZXL778DmRdZEX0RQA=,iv:ke6krfudgAMihnNbVGcztAS9zfahO+5T+cdJlyhMC3g=,tag:JhiYyfdJJEXmQJZ7/+jM+A==,type:str]
    SECRET_ZITADEL_CRDB_USER_PASSWORD: ENC[AES256_GCM,data:GHXqn8Xv3/q7H6cYei2GK/SHCcwMuT3bUas=,iv:OE3xA+W/q1BFmNS3/eDJgvZvDOV4/X50hHIdWeaNCk4=,tag:ey/ckngUyJ971DYiW5NbeQ==,type:str]
    SECRET_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:h3dXND8OL0c90BOTxamwUh93h250bLKCQuuAvCPgRLYO6yauNQ==,iv:x9EI6l8D1X0w911dGtYk/b8vVd7q/SHPy99I83obrIw=,tag:N3Z2hNI9Gjd75xSSSiVGYg==,type:str]
    SECRET_CLOUDFLARE_API_EMAIL: ENC[AES256_GCM,data:CcRuE1LyH4wbUVUGhh7JszDu8CqmPw==,iv:V44D/HmOiJQ1BUEWjd5hEziybHt14LPTOEEIZFOFL58=,tag:r94n3+i8MGwFYDxEZFTE6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Y09uTGJwLzFDdnFDT2M3
            Zm50Tjh4czNaVUV6NTR3OGpidDVMdmVwQmh3CkJUY01veEkzaWRsNnVwUGFxMDhK
            TXlMdE5zYjdyMTdwSC9qVXFiZWdVTkUKLS0tIExvOHhaVGZpYXFGZ1pnTEpVenB2
            S3RGVWR1Wk9WU0ovakhpVnBNNytxdjQKPUUIL2e/IRFYPRmfAHF0be4Y9WDrgWTd
            8V5bWPVGY8ROovWIcaQYvVWPsBPJ7gcmD0SnNLCnKnXjt4MvMuJuSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T17:30:54Z"
    mac: ENC[AES256_GCM,data:eyuho3NTQ001rQtyxtN+H67H7x7GGq0X8jlks0wDoO7haeM/I6a6R/KFEkLl/ztaB/zFBGti9lS/GdYK5oaPs2AnGCsiy+6nSNo0VHLYY4BeVi9ISt/I4iwiM3ENnlXBoT7UBDvAL+1JaOetx0InO6JjKg1euKndNa8Am0KwMTs=,iv:dP3fgcqc+hQ7UVBzZ6ybF3kJoIgYNp9XLigQELTlLxo=,tag:cmFySPdMzSr64+FzjyiY6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
