apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:HBy6vh4d8Cd1bMslsmpzWNGu,iv:JqBxB+G0rsl5tqvIutgAgVFzovLg2ZsEuDts0nCl8WA=,tag:6Kk1xUfreYQzJVayiWopfg==,type:str]
    SECRET_MEDIA_STACK_IP_ADDRESS: ENC[AES256_GCM,data:fwP+AoQBPaFPLBnQJA==,iv:7bOELUvrYRzl0EKI1j8hqr1TDKUJdErTQgM8u+lwGWk=,tag:GiWU4FUPRwGTSMJIv1rkFA==,type:str]
    SECRET_CODER_DB_USERNAME: ENC[AES256_GCM,data:Bkf1aCU=,iv:2pKQqj1HOZjIbCwc4pAlYn7bhR74k3wQQZB8DCHawpQ=,tag:dYPA3u4F6ibpDbqVts/f1Q==,type:str]
    SECRET_CODER_DB_PASSWORD: ENC[AES256_GCM,data:SJT/DKA=,iv:hMOHU1vjuoZSv3MGjv4HwIsxwRHR0RVRG5xrJ4SyCqk=,tag:VHp/I2KjnpTD2UyMFInBcg==,type:str]
    SECRET_CODER_DB_DATABASE: ENC[AES256_GCM,data:9+LvTVw=,iv:6ZC/DhsyGkplJ1NjXx93hu2jW/8YokBTVMy3HJ4qn/8=,tag:2IFNt7ZQsYrTvy0yUMgBMQ==,type:str]
    SECRET_CODER_DB_URL: ENC[AES256_GCM,data:3+nSCkY6kl9/2Dz+p2atcfaYd/Wybq4bMsLR6BEMnchpEb+KzTIKFaSBdvrGewhfPvv3MIrq5iodNL4FhsuqYSsd3w5kpPQKyQf72pCNbehrxkC4XHyMw0YFPMc=,iv:9IEV6a0X3Wh4zw/URR2Fi9pxNncY2dVCIQ4U53qrpEA=,tag:3ChAf8eHaBMgGHHoGAPg8A==,type:str]
    SECRET_ZITADEL_MASTERKEY: ENC[AES256_GCM,data:wEt3e/xiMWglbMG+jEvZtBtOXET/xhB1CU2edmGCgzA=,iv:oz4KxBfA9TA3jNNe/u6bZBpFXPyMSPLCg3rusTEbzss=,tag:Q5rzj8JLMo6tnu7Jqp2/ZQ==,type:str]
    SECRET_ZITADEL_CRDB_USER_PASSWORD: ENC[AES256_GCM,data:vXSrcI41ZordcoG6maCMR/nWJjbNU3zeEm4=,iv:6oQZoY/cbnB/qzpQWVpcylgc6WjKMV/2zrUqYy6Fwo0=,tag:Eja8x52Y5Y66K6y13n6H4g==,type:str]
    SECRET_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:aYpNp+FMvIrW33TIFE1LsfLlpnNBddMxKwQxvYYuRI4BtFk8Lg==,iv:GLbn0AuMM5+5BHXBvnNkbrrFMuNaKsZNZXiGbYrrSdI=,tag:/fDji1tFdV+XPfYRhvFwPQ==,type:str]
    SECRET_CLOUDFLARE_API_EMAIL: ENC[AES256_GCM,data:1oXO/SWnHJLQsSH6yP+661nxOmO45g==,iv:y9/4BtDFxQsSgAd3Vendj5WC3jgCgu2GsKrGlZ7Yb30=,tag:Pe2X444Pm2a/Qu+KPZLT6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWGR4NWRjRnppK1kvUVRT
            TDNKSnJjeTFxSDBON08vOXdrNUdUMVZ2d0QwCnkwWDZqVysxZ0RWVzFSVzNSVlFZ
            QS9YTVNqbEROVmRwT0hrdVJlZm9ZTVUKLS0tIFY5MkRDTUtLKzA5MG5pTzBGT0kz
            L25uNnhzV2VmUUZFWHpIOFBVNEtKZmcKUfrnbXp4HT3IWrfmpfVe13c7STkwC5FV
            2sly3GO7Qd/5CyRjwY5n63yR7DSTOckbpeudutZGnEHrq2shCgISpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T18:16:12Z"
    mac: ENC[AES256_GCM,data:v0VOWDjFNrCJv0yCJP6+RmjIcga+M6d+TxAyY6aa9HieHjcF0d6qLkdgDqSiU9mK1GzPY0D5v7Plc9Kq9rruwOp2/ZE7YDAXTjspcnb8ELg7gT45rDWxY6meYxRS5STmIRfrMSW2lwjdlpAaW70B70mfqC9eOnCWMX1WnmH5W5A=,iv:4sn7RGMsT6qK8umY8kC8jMPfEKPWqxNZG140ZX/Wyg0=,tag:OFiMnfjb2PvJxxsE6i0opA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
