apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:4+hgtg6aQaG0h83oaBG0tkea,iv:08XbddEQFzjWf3rb3ljIdQ2jhjMI5FkINv55lpEUw10=,tag:5HjVsyvrHcfp1clY8MSGaQ==,type:str]
    SECRET_MEDIA_STACK_IP_ADDRESS: ENC[AES256_GCM,data:J4MNJCd4Dk2EYw4DVA==,iv:Bhj7bWr0/Tb5hNo4rVxTXz11eR+CnqBVunKRQiKJg8M=,tag:7Jn5iZtjUidbDNn1aiUA7A==,type:str]
    SECRET_CODER_DB_USERNAME: ENC[AES256_GCM,data:bfSwfDU=,iv:Mp1Xwu8+KvouG2aTBVmkLFij4KJRlNzCwB1a5CYgrHE=,tag:0qV3VuXMjZolQhrWbuYY5w==,type:str]
    SECRET_CODER_DB_PASSWORD: ENC[AES256_GCM,data:BQ42CMY=,iv:0MBaj14475leZH6OHU+32DDVnh2BAoM0tZUiXTvc/eA=,tag:2PcUflZDUKHLh2rqna03Ug==,type:str]
    SECRET_CODER_DB_DATABASE: ENC[AES256_GCM,data:cLu9yQM=,iv:ZdGpp2CFhoa2QZHghkFaCZg5mtDZRtKDKgAHpV1Z9rE=,tag:awIDjg3DOgioAgfJjNmrFw==,type:str]
    SECRET_CODER_DB_URL: ENC[AES256_GCM,data:dJGjUqapta0Q9uUcFhBGkgqxsCby1wQLi28u7PdrR4qtzAr9ER85CQPNHlB2CLhEEAiCNmxkem2pBkbAvbyurlFeeLqesSpYA/H7AS4+x4ZQkI7AYBeRy5lou84=,iv:O+Ims/TSzFnjvnYv93mVv+Z5q5teqSGAUC2iMN2C+n4=,tag:3Hh3AyBJRIAVp15hta5jZw==,type:str]
    SECRET_ZITADEL_MASTERKEY: ENC[AES256_GCM,data:l+4oyu+z14tbs3OR7VU/1zzG/hJfiS8N894ACEeZdkc=,iv:MUM8rYcsRS0jBM2HGAixMQN1pZy/m7MlIFcHlqwLoDw=,tag:lYI6atWzPmx0z4PtQgJOCw==,type:str]
    SECRET_ZITADEL_CRDB_USER_PASSWORD: ENC[AES256_GCM,data:3koCXzij7mnpl3nF8zzdIb1GLTJ/+d0TsHU=,iv:9n0V1L6xOq47mPKSFr6squXPKMY3es9VBd2m2cvW6PA=,tag:9Y6tMVLmN+VIiorrnCpuPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQWNUdTJNcTc2dmhmL25F
            SlU0ZTRKcDBqTk9aWWVqOU1YNCtoNlp6SVNRClZVRzFodU1JVWpkMzRLUm1CbXFS
            Zk1SanRWRE4rckQ5c3JCM05XSHcyZk0KLS0tICtiR2s3NWlIWXBpQVE2SVBlOGFG
            c3dPREpNcTNXWUhWSlBlbVRMdUxnSkkKTpionq8p46+PHJmoxUOqUvNQxMN7vCTA
            ZGO42ZrW0w9mR8L43QaavFyQPo0gThQLcbdxbF7PVI/7OQhq0upVSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T16:14:58Z"
    mac: ENC[AES256_GCM,data:dhrQ1SifNtcopXJbN5Ga8OlDmpBw2XkF+WKlbY4rFzEojOym+PR9mMvxOTJn6XvI56q2u5trND4otMI30bmCP3HzZndIm1IyzSZDbnQsKkLCs1CxsJZTAcWmjAjAq3u/fsyWAD+20OO4f49y6OmkQoDnjh7HpfmjM2W5wYeC/D0=,iv:167Px1RaEtxGJZY9Eup3xPwEQYAXKMdiBWKdliK/XS0=,tag:Ck1ZldxeeVlnwiErDAAQSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
