apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-sonarr
  namespace: flux-system
spec:
  interval: 1h
  path: ./cluster/apps/media/sonarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system