apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: tool
spec:
  interval: 1h
  chart:
    spec:
      chart: coder
      version: '2.6.0'
      sourceRef:
        kind: HelmRepository
        name: coder-v2
        namespace: flux-system
      interval: 1m
  values:
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          value: ${SECRET_CODER_DB_URL}
    