apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-release
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: utilities
    app.kubernetes.io/component: rollout-utilities
spec:
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.40.5
    chart: argo-rollouts
    helm:
      valuesObject:
        dashboard:
          enabled: true
  project: utilities
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true