apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn