apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${SECRET_CLOUDFLARE_API_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: ${SECRET_CLOUDFLARE_API_EMAIL}
            apiKeySecretRef:
              name: cloudflare-secrets
              key: api-key