apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:7NbgnycRewr93vh0Uy0jqn+ILcU3K+6onCH/JZ+e7PvVJ/mtDw==,iv:TmGmku4YtCkw8MkaTcwf/eoa3ciyymWXOU8ljqC2C0c=,tag:E/gOrqYnbQIMCgm/3X0fVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNVJLdFdYY3BNVm10RjFG
            Z3JUN01neVlNTmRodUt4UUcvdWhkNEFDakVrCk15Ty9xWVhSSDcrMlFaeGZVSFR3
            ZnhCUmNLTTgybjZhczVUNGJ6dkNlajAKLS0tIEpKWUpPeWdkNVgwMlIxeEVpWjFs
            Q09rZnAzOXNzRHdDbFdhM0pxaXI0ak0KevJTuGiTAhkBbfMvpVc+B7uuKzWvF1b5
            2esKxiqxeSzhqFCgIrgBBGeLmI7XsuSRNTUKaOXAgyTtu8TZVhVsjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T17:37:10Z"
    mac: ENC[AES256_GCM,data:ckzHXsxJ2V4RGm7PoR0tLoVa9MOkBHEoCqZ+P6UeKZHEYReSdHo8AMObAPp9ww4xUDjUqQAklrPFNu6LpiNRlx1D86YTYS0W2o/QLMkXyrEbdlcc0/AhCCxJTkmZowG4LYOglgbMNWMPdpopt2Ks/z/68F0OtiZajLrhmPcNJZE=,iv:YBLmBK5jVORy+NbNqqMvAS85+xbO2nZz6fEFfGk84W4=,tag:2VodKYp6AfAtyV5Qoa7MQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
