apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:iyMo45txbmDcEEj7YUU2wB7c/tzM60LId1wgy044/32wc5iynA==,iv:5GxwBHWrTpBJmY5K4L/HXbof46q/wSwQ/KU6jAOQg2U=,tag:BrrqdPz+HhaNHP1nEndPmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdENXbCt6T1dSUTdxc1Nm
            M09mZldZVE1QTWlvYVZwQTlJMkdZTE50dkVZCnZZajd2dFJTQmViMEtITjVLa0hZ
            VUlyQ3kwYnNDaG9OOVM2NEhpSkhyRlkKLS0tIDZtM3Z3b1YwYzNuRlhsSVdOVE5s
            V2dpN3lrSmtFNXAvSk1LQmU5b0xla3MKPF7l/dyEumytpjHcAywQ19ef2rR3avQn
            1HEnJaGqvQq7ANUr4WNezcjHst1La5iZ5e8fG2dd25r7pemCsuhADg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-01T13:13:20Z"
    mac: ENC[AES256_GCM,data:E5P6ePj5TWXpauWBZqNJHPy5y+GR4Cwc3CqVFE5pltCcXI6xtjVTA5NH+/lOeWryvAYh+Up182ykehjsJNWanvOp4USLgC8NJGapCPlY0l6g3BeZ7KaQKZbqxnAkoepJChTWQMWX9WXTBj5aAOP4RREhRbnpfNMeTDcODxZub1w=,iv:CaFVQs1enGbiZLfjH/ly4rWOqXU9iD03PuCjICViT90=,tag:Kl7sAkyXgOqxHc0Ja+gmbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
