apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:mejqT2FB2Z08ne2z48uViTwQtFKDPyT2g9s98qhD/CngEBTR7A==,iv:P3mNp7lkKI+K+X7ROLdQvins8KkEfA44aMfeBzmKpac=,tag:D1swEUx5pj26ORQPJwC7nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dTBLZjdpMjFkM0hvMk15
            VHI0RC80Vmo2dUU2Nlhsdk9IVnd0dnhyZlRZCjUxTmttc3ZBbTZWYzdlNjBQKzda
            cWdSSDd3aURrczZ1ZHBkT3RGbUpFRm8KLS0tIEtQOGtxaTZSNGhvT1VPSzJ1NWVs
            Y2lFSkFjdEhWRFpRaE0wSXl5eTl3QlEKLZNkkSnFFrqdv9N3MnrxLMVwgPUSf/Af
            Xm29yLtVxrZrKoTadL8IudO0jjaNTmB3hGetpk9dgTticoNJexZvGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T17:12:21Z"
    mac: ENC[AES256_GCM,data:BenSHUMV0ftIXl5EtYe2vehEUMg3qvLCpsKwYlpq+UH1T3kAsv9cd6Pc3tjS0Eri6bvSz6QZSgqn2KAloF/hjCzB1tWaRsgoLHA1VoBJd3C95J/0AROd5EwJ/Er9J0IxPbq5ZL8FGRVp1XzEi+riEhY4g6e2Ax5nJSc+RyLDsKw=,iv:xZ56305HmV5wxWRa4NUYAvOql/jX8EBJFouU1bPbDUI=,tag:PSI4Pbl9vyMMYaHixNfm3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
