apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:0W8y52Sfqist42bMbGSviQc/6iW7IeAyRLXUtsU3YX2bPj4D3A==,iv:08LsNiUfnym9yyZYOpHI7SE9RGY3qkzn98rLlDNu3Cc=,tag:QTJYs/lcAUXI2/XOXWp7aQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb3hTL0xxM0pvdERxUWtm
            UXVrZVNUdWhJWmRvK0tvdW85RU5YNGdnNEZrCmJqZ3Q1WDQ2L0tubjVOanJmWk1D
            WlBpSkxYZk5HNWErdy9pL0c5YkkwaW8KLS0tIHF2VGZ5SEViRGhSNU1MRDhFa2pT
            dHlVc1dVZlRFRjJ4OWFCRUZPOUcxdXMKyP4/M+98078s76SZBf11GFOj41YIwhER
            sOD2LpTTX6LGShZlJqaxEqTCy380WujXrrFaJTd3g4IUjgh4wKTxYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T17:22:06Z"
    mac: ENC[AES256_GCM,data:20Mb4K+FhLPXPPI2/KXgJE/z+ldEkcyaoClchLDrHiVO0o7Gfqq5x7OXILX/4KYYjMLZXgeVRcOYtqza8eCvDgs6JbeER9OWHvbsOCgA/fZf176e4E1Uxlo15LxEfXw2+zlPsNgo/+11OGPwIIeH2HokYMmxnBmqSzkB0IvZYck=,iv:qCTMKY8xxdFRoZbbReVjBjPvGR32B9GvgOyI78Vu6eU=,tag:LnqUqHPjYQxMIK+ixlXrmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
