apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:urYJmhHDV5m3h7JAD9lldAeT8nsv4Ht9viA1t9nPxFhn9wTy+Q==,iv:1zQz8+wm8cCH6GwE3/KmR4qISwEe6DB8IzGx8RV8i2Y=,tag:P4bkZERpUZCbr8PaIRW8bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMUFoUHJ3d0FlUlhUdCtL
            QSt2TWtMblJkeUpTckw0WDRaelVjU2dOMjJVCklMRU1jL3R5N3Jqc210RkpYcXdE
            VGEvQ3pQazUxVC9UT1JyVmE2RmdMSkEKLS0tIDExc0p4WmQ2ODdyUGNFMG5qTEFm
            Y1VIamNRVDlKSnR6M25DelNxWWlSdEEKDbMvLQZjcy7DuMGNtgiZQz/Gh6inWPcW
            aEawYmKTLfd0PJQAo2iV+0GkxYVNLC2eZZDlbAowt4UXxmjuG5zSjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T08:53:10Z"
    mac: ENC[AES256_GCM,data:Zjlk1vv8iPQM4c2EMx7Udm41IMyN5xaCN2T3kUGjs4drYcC6jtVsZ3TTqZbZlsiuQZtv+AQ9seSwo8Xc6JiNY8tyaXETVD/0Y+6V6HxkJNEFGCgOQithDl+IcB6XccgCpddbCIEJ7FDKD4Z2J+KBHGOKX7JAK9FT+B4tkdBYF7Q=,iv:995VTT3kogQq9guOvKmmej6KZxm20M9gdNpqBVa02+I=,tag:xyPlWUCgAiRcRYHD7WY6vA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
