apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-zitadel-db
  namespace: security
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn