apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zitadel-db
  namespace: security
spec:
  interval: 1h
  chart:
    spec:
      chart: postgresql
      version: '13.2.25'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    global:
      postgresql:
        auth:
          postgresPassword: ${SECRET_ZITADEL_CRDB_USER_PASSWORD}
          username: zitadel
          password: ${SECRET_ZITADEL_CRDB_USER_PASSWORD}
    primary:
      persistence:
        existingClaim: "pvc-zitadel-db"