apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: networking
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster Networking Stacks Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: traefik-networking
    server: https://kubernetes.default.svc
  - namespace: metallb-system
    server: https://kubernetes.default.svc
