apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress
spec:
  destination:
    namespace: traefik-system
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://traefik.github.io/charts
    targetRevision: 37.1.2
    chart: traefik
  sources: []
  project: default
  syncPolicy:
    automated: null