apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thaddeuscleo/cleoverse-gitops.git
    targetRevision: HEAD
    path: ./workloads
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
