apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseer-ingress
  namespace: media
spec:
  ingressClassName: traefik
  rules:
  - host: jellyseer.cleoverse.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyseerr
            port:
              number: 8080