apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-jellyseer
  namespace: flux-system
spec:
  interval: 1h
  path: ./clusters/my-cluster/apps/media/jellyseer/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secret-vars