apiVersion: v1
kind: Endpoints
metadata:
  name: jackett-svc
  namespace: media
subsets:
- addresses:
  - ip: "${SECRET_MEDIA_STACK_IP_ADDRESS}"
  ports:
  - name: jackett-app
    port: 80
    protocol: TCP