apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redpanda
  namespace: infrastructure
spec:
  interval: 60m
  chart:
    spec:
      chart: redpanda
      version: 5.7.34
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: redpanda-data
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    tls:
      enabled: false
    external:
      enabled: true
      domain: redpanda.home.cleoverse.net
      type: NodePort
    service:
      internal:
        annotations:
          "external-dns.alpha.kubernetes.io/hostname": cleoverse.net
          "external-dns.alpha.kubernetes.io/endpoints-type": NodeExternalIP
    storage:
      persistentVolume:
        size: 3Gi
        storageClass: "longhorn"
