apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: infrastructure
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:H42xGXRU8w==,iv:0a0+nN2ruitsen9u8w3E7S55F3YLYsE2LJEd7Q2Wio0=,tag:MB/LMsEgFQXN88ABwE8pnQ==,type:str]
    password: ENC[AES256_GCM,data:8WCe/glxt44kEew=,iv:RHf1cLNBqoOs1pOFX/FdBkSc8AWiNULNUKkzNYAa3bQ=,tag:IJhSjd+pIZ58viHuOGbqGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsR3RadHYyWGd3emRPTUdu
            MnRKZnpXZHlNMHN3eWZLQjlZU1QxT2ZxblNBCmRLajVtbWJiQnhMUmlycDdURnN3
            Tk1pSXYrZm55NkZLRVAzN015dE9LaXcKLS0tIE5ZYndBN05LMFhHR005VUprRjZx
            ejhnakc1bElZZEp0S2xCdUlSbXd3QlEKoOsk32MPO8G+1MozIRWXe5vnbmyAEqDt
            9UbTqb5dCGHt4fo0yJ/cQ5pMHVlmKy7BRZXqLhhpeqLTLoHo+QCtXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T17:22:06Z"
    mac: ENC[AES256_GCM,data:u6mCyldFHgRmDY4DTouaZ0bGj5eiqmh9fOkUCwUEmjlOSbol/6TAtP2GDG+NAkM6R+g8Fi2rBw+TceZXRbWoZEE81oeBrT8SpPb9bH8jG8uvZ0XL44sbTqLAEBQxLXk77Mnw4yM2/QrB6BOHFzcSUxGyYfqgMDtdfrcTPQqNRYo=,iv:/ba0bMcpBzsyDhOHerU9m+Wy6X5FqCo2no0w93ds7wA=,tag:oLDlvWD8amdEMHalljWIrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
