apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: infrastructure
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:cOSCqWoHqQ==,iv:gyD6lBdOY0tweiEk/b4G1o7CZkJEWNLFMXBcA8Z2yas=,tag:AaIoMM/hN6KrrcWYy5HrZw==,type:str]
    password: ENC[AES256_GCM,data:k45RXEvCCg18Hyo=,iv:rG4rGcjOgD2CkWREhO6XrPKuLhPLgV8cyAa+FXylXqs=,tag:x72ZdR4wcuGFABUvZeabwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoU1ZmbmJZOWNweVVBd0J0
            S0ZjTWxtNWYyRkVPb2dWSzlSWnppcmxiTUZZCnc1b0d5QVAvbEJxb3hBVlFOR3E2
            N24vc0FZSWtyeTdOMzIyZ1hmaWcwRHcKLS0tIDl2T0VvU2V2YmFGMmVCQ1Zzckc2
            c2V1RS9hYVZjRGJTMDFvUHFRMWplMUkKTLXpAiuHBtVow4tlHPi9i2J+2Td7ia9n
            YDrblcQMWGrGGfSVaS4P9e2aKiTrS8VrO8aavyCXUaQreEoMooSqsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-15T16:21:23Z"
    mac: ENC[AES256_GCM,data:xykq9AET1NuKC+g9g5z+Z5OMQvtWsVE7HzLF6K6OyehGQC1NuynYMRcII4HlHjk4FSs5ElrsoLllVI20oEzR3g8L7amuZyaq5kXfu8XUSpv1bB9ANTlAl3LxVLqs3ew/f4WjkiFc6YKsyFb3QO0Vp1ArsCQB5boK2jKHM6AxsEg=,iv:Fs5QO79R1Kw11fCIRKrZjRhZ1hXOgJB4lNbaWT8+6/4=,tag:VMdHpsGE1R975gsvd0z10g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
