apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:L6KOKur+ssTFQgRG3B4=,iv:J101wlGxasl9IbyctGPw23DaVygHz6m7FzyvsQolFu4=,tag:jL6AADanyBevnyDh/QAvwQ==,type:str]
    SECRET_MEDIA_STACK_IP_ADDRESS: ENC[AES256_GCM,data:rHyj0VA/p7XPLic1jg==,iv:8+4/jZtzVe8gnfZYk8ZDCI+2G1OTusj91/H/VuakqVo=,tag:s4cwSTsHBDOlnHg8wbKD4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Ylc1Q2hMQzVxU2VtVWJp
            L3R3MzNmNG9XR00rRU0zNm9uTXBicldZVzM4CjFsYmxYT2NPK1RRVXNKU1JNRjlX
            NkNENC9RMHNBbFFHS0Uxbk1vT3lJN2cKLS0tIGgvM1V0SkZOQ1FPcURZeXVRODJD
            L3I1Sk05TndxaWFIYzllOVd3RStpc0EKqsVyzn4YLB2np9+3MTfodJmqcHYODUuP
            JK1JMpuLzIrJMmGh7XnpB3GlgMRlegGg+qBWzTgUTeb3IaptgS/Fig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T18:57:57Z"
    mac: ENC[AES256_GCM,data:L+FdgPnYl6fehjhbJyOsMxQx9be9RQh1k2fNnKxRXOKYka2nKQpi9dcQAv0bY8nKSJ81bAUUNY7hhY1yD+eCrt/XaT16gmG1MNtUxnKh5gb4sVR5BOR2+bRMI1S3kn6XUoY/zQMHfajnHtCNQbIJcE9qP42SbwbgUzXiN8t1vos=,iv:wCNFrnwkTAaNdFGocN93Nequam4NTPmjp/VHT5k7jNY=,tag:HKi6ir6cMnfumiP+RnnViw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
