apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:HNSLBLBz4r/POv9/3Y0=,iv:Lu7uoss6bgo0ASUENGrMuqtunaOGqQOYBGGOwO0gwAY=,tag:coet8sM9cRXZSwCaEH97fA==,type:str]
    SECRET_MEDIA_STACK_IP_ADDRESS: ENC[AES256_GCM,data:zWp5Zf9eGkUMINdlKw==,iv:WgjH6JBl2A3zEUGz5LhUIB1OHQ9/NhFM1D+U3xV3eiM=,tag:c0LeyLe6zyWA3peJLcp57g==,type:str]
    SECRET_CODER_DB_USERNAME: ENC[AES256_GCM,data:4DT2hvQ=,iv:LMpzgZOCSEw3UHVgkFHgzvN6LSoYYhwL1iwXBu5VflQ=,tag:LbZyEZ9Ncyb+ee3oC5QI/A==,type:str]
    SECRET_CODER_DB_PASSWORD: ENC[AES256_GCM,data:Q+8UnIM=,iv:oDyCUmSAUhSm4REOjz858h/u1yCmLcW6JJJc69LosVw=,tag:4HsdPuQSO2MPPYR9/92K0Q==,type:str]
    SECRET_CODER_DB_DATABASE: ENC[AES256_GCM,data:DKqI2DE=,iv:udo+85lfSGVDADWoEtqjJgN2UfVTWsIv9h2s/yo2W8s=,tag:HoT6Z85IoGTp44/L0STx1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRFVjYWMwcnJYempucHVM
            eTVSMnB3NXAzOEh0dktQTStIWGtyTDZ3Y3g4ClpHMkpyNUIvM0FvY2JwbjFqaGF3
            akNBZ2UvZXdGeTdBeFBKOUlrMzM0NGMKLS0tIC9Jbi92bWgySHpwY2RmdkR1M2tX
            RWNmcU9WNkltTVJCbThLZC9KN0NvYkkKw7vbVUrHxTco6U5bwbVgzjKgmERl5/Rs
            Nbj+QDEQkQC2VwRLvdcgUh5cxSI6/H76jBR2z5vVJmy5ZqhanCZHig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T04:03:48Z"
    mac: ENC[AES256_GCM,data:CCCQfkxyanByzctLrb3QoPdqEvPf7vrMEYlN2CIW1IRGFn+xg1/g/AapLARapLWkBryTSF4hU6meWSzIlUD+LfEfwQluYVFjBe7J4i+lkVoarQRgwoImNJCuqObhK0qOuSl65xTQSPWm07/9ZBRn1S96qyX9LR3qJvGTFc3vaPE=,iv:swEYlBqsGeY6Yfv1SYpzo94V8BcnOzk7JhTXynuNMmY=,tag:Zk1IAGqE2IDnYaRWUDc2XQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
