apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_LOCAL_DOMAIN: cleoverse.home
    SECRET_MEDIA_STACK_IP_ADDRESS: 192.168.0.152
