apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: utilities-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: cert-manager
            path: cert-manager
          - name: argo-rollouts
            path: argo-rollouts
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: utilities
    spec:
      project: utilities
      source:
        repoURL: https://github.com/thaddeuscleo/cleoverse-gitops.git
        targetRevision: HEAD
        path: ./workloads/utilities/{{path}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true