apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-longhorn
  namespace: flux-system
spec:
  path: ./cluster/apps/storage/longhorn/app
  interval: 1h
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system