apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/part-of: root
    app.kubernetes.io/component: security
spec:
  project: security
  source:
    repoURL: https://github.com/thaddeuscleo/cleoverse-gitops.git
    targetRevision: HEAD
    path: ./workloads/security
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true