# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: prometheus
#   namespace: monitoring
# spec:
#   interval: 30m
#   chart:
#     spec:
#       chart: prometheus
#       version: '25.6.0'
#       sourceRef:
#         kind: HelmRepository
#         name: prometheus-community
#         namespace: flux-system
#       interval: 1m
#   values:
#     replicaCount: 1
#     server:
#       persistentVolume:
#         size: 1Gi
#         storageClass: "longhorn"
#       retention: "3d"
#       retentionSize: "500MB"