apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: tool
spec:
  interval: 1h
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: coder
      version: '2.12.3'
      sourceRef:
        kind: HelmRepository
        name: coder-v2
        namespace: flux-system
      interval: 1m
  values:
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          value: ${SECRET_CODER_DB_URL}
        - name: CODER_ACCESS_URL
          value: "https://coder.${SECRET_LOCAL_DOMAIN}"
      service:
        type: ClusterIP
    