apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: tool
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: '2.0.2'
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    env:
      TZ: Asia/Jakarta
    ingress:
      main:
        enabled: true
        hosts:
          - host: hajimari.cleoverse.home
            paths:
              - path: /
                pathType: Prefix
    hajimari:
      title: Apps
      name: "Thaddeus Cleo"
      darkTheme: espresso
      showGreeting: false
      namespaceSelector:
        matchNames:
          - tool
          - monitoring
          - media