apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hajimari
  namespace: tool
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: '2.0.2'
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    env:
      TZ: Asia/Jakarta
    ingress:
      main:
        enabled: true
        hosts:
          - host: hajimari.cleoverse.home
            paths:
              - path: /
                pathType: Prefix
    hajimari:
      title: "Cleo Hajimari"
      name: "Thaddeus Cleo"
      darkTheme: espresso
      showGreeting: true
      showAppGroups: false
      showAppUrls: false
      namespaceSelector:
        matchNames:
          - tool
          - monitoring
          - media
      globalBookmarks:
        - group: Mail
          bookmarks:
            - name: "ICloud Mail"
              icon: simple-icons:icloud
              url: https://www.icloud.com/mail
            - name: "Gmail"
              icon: simple-icons:gmail
              url: https://mail.google.com
        - group: Repository
          bookmarks:
            - name: "Github"
              icon: simple-icons:github
              url: https://github.com
            - name: "Gitlab"
              icon: simple-icons:gitlab
              url: https://gitlab.com
            - name: "Docker Hub"
              icon: simple-icons:docker
              url: https://hub.docker.com/search
            - name: "Artifact Hub"
              icon: simple-icons:artifacthub
              url: https://artifacthub.io
            - name: "Hugging Face"
              icon: fluent-emoji-high-contrast:hugging-face
              url: https://huggingface.co/models
        - group: Social
          bookmarks:
            - name: "Youtube"
              icon: simple-icons:youtube
              url: https://youtube.com
            - name: "Twitter"
              icon: simple-icons:x
              url: https://twitter.com
            - name: "LinkedIn"
              icon: simple-icons:linkedin
              url: https://www.linkedin.com