apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-coder-db
  namespace: flux-system
spec:
  interval: 1h
  path: ./clusters/my-cluster/apps/tool/coder-db/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system