apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr-ingress
  namespace: media
  annotations:
    hajimari.io/icon: simple-icons:darkreader
    hajimari.io/enable: true
    hajimari.io/appName: "Lidarr"
    hajimari.io/group: "Media"
spec:
  ingressClassName: traefik
  rules:
  - host: lidarr.cleoverse.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lidarr-svc
            port:
              number: 80