apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: networking-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: metallb
            path: metallb
          - name: traefik
            path: traefik
          - name: external-dns
            path: external-dns
          - name: kgateway
            path: kgateway
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: networking
    spec:
      project: networking
      source:
        repoURL: https://github.com/thaddeuscleo/cleoverse-gitops.git
        targetRevision: HEAD
        path: ./workloads/networking/{{path}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}-system'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true