apiVersion: v1
kind: Endpoints
metadata:
  name: qbittorrent-svc
  namespace: media
subsets:
- addresses:
  - ip: ${SECRET_MEDIA_STACK_IP_ADDRESS}
  ports:
  - name: qbittorrent-app
    port: 80
    protocol: TCP