apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder-db
  namespace: tool
spec:
  interval: 1h
  chart:
    spec:
      chart: postgresql
      version: '13.2.25'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    global:
      postgresql:
        auth:
            username: ${SECRET_CODER_DB_USERNAME}
            password: ${SECRET_CODER_DB_PASSWORD}
            database: ${SECRET_CODER_DB_DATABASE}
    primary:
      persistence:
          existingClaim: pvc-coder-db
    