apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-outline
  namespace: tool
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn