apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: outline
  namespace: tool
spec:
  interval: 15m
  chart:
    spec:
      version: 2.3.0
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
      interval: 5m  
  values:
    controllers:
      main:
        initContainers:
          init-db:
            image: 
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: outline-secret
        containers:
          main:
            image:
              repository: docker.io/outlinewiki/outline
              tag: 0.74.0
            envFrom: *envFrom
            command:
              [
                "/bin/sh",
                "-c",
                "yarn db:migrate --env=production-ssl-disabled && yarn start --env=production-ssl-disabled",
              ]
            resources:
              requests:
                cpu: 10m
                memory: 400Mi
              limits:
                memory: 2Gi
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: "traefik"
        annotations:
          hajimari.io/icon: mdi:text-box-multiple
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: &host "outline.${SECRET_LOCAL_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
            - *host
            secretName: lldap-ingress-certs
    persistence:
      data:
        enabled: true
        mountPath: /var/lib/outline
        existingClaim: pvc-outline
        subPath: data