apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: outline
  namespace: tool
spec:
  interval: 15m
  chart:
    spec:
      version: 2.3.0
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
      interval: 5m  
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: -1
  uninstall:
    keepHistory: false
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.6
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: outline-secret
    controller:
      replicas: 1
      strategy: Recreate
    image:
      repository: docker.io/outlinewiki/outline
      tag: 0.74.0
    envFrom:
      - secretRef:
          name: outline-secret
    command: ["/bin/sh", "-c", "yarn db:migrate --env=production-ssl-disabled && yarn start --env=production-ssl-disabled"]
    service:
      main:
        ports:
          http:
            port: 80
    resources:
      requests:
        cpu: 10m
        memory: 400Mi
      limits:
        memory: 2Gi
    persistence:
      data:
        enabled: true
        mountPath: /var/lib/outline
        existingClaim: pvc-outline
        subPath: data