apiVersion: v1
kind: Secret
metadata:
    name: outline-secret
    namespace: tool
type: Opaque
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ZWmoXM2nww==,iv:IIyPXXpVqKBT1DdSLpPJdhcQo59pM8e3/jEla+EjvDA=,tag:AbPzwGiesaNiMmlgNcW7kg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:wjnTRkXeQgp/X3hgrrsSKnUj3BaQCXcvPsc6YdJ2Dy2xD0l3l9TADvyZ1Q2jxkfqjw==,iv:unOEyxGNyKtsoV9M/wmbQWTXLqAzLRBCbWdmc+U/XvY=,tag:nRZdMlILAl0VV7OGJGRmXg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:1C/9KpQHIlF2kddwTQ+DCTvx1PZZRWiouaOxB+/QT7IeZE+ZcKCSIA==,iv:6sEib85A77IsAXKvvfpb4EtEcT/6Epzh49ChjwC04dA=,tag:cIEwKH8wueVKMw7nUFtvww==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:/EwkYlnm+olrdfqSIpSHZvj0AkH8lBOQ1zioX5hIY7wEwi7Xz6+Z2g==,iv:vIN9HS/T6qn+JNsYgeamm/0dzWn635jnSgcIjKckPLQ=,tag:/rOlVIIHaL77TICSP9PVdQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:WlDNSEq3g232MG8bAz22M/k62bcjrygmmDOH,iv:IlhYdYloCdOP+Rg64p92HTqlNdG/mNB9yRMu9486yt8=,tag:5Y6eVrc6Qcnqdk2mtnTUEg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:+gdIkg2jHP3ZwUOzIekxpOEwM+EgLuu446WDGVumipMRQbK0sinmFV74GbGUTHaqzGTZAQTUvb8intyQQyN7QBuJfca7nA/JPkv39VLfmlUDmolmVyxn+fWyHp494OFWQppiRdMYvya6m8zy1qAjl52qpZLE1eRRedgGXMTmf4C9phyTN6dZnsFyiEbFF6c1TWIGzRPx,iv:uAxYouQB/vBce4isY/pNgw+CkztVvzsjpVSCFxXN2b4=,tag:mj1XcohKqx0w0Xm4NigTuA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:f6kWV5lLyfZDltiuno5HYDKa6Qz5vLkGc9HpygtOh74fM3qr2s66zlIntkGKCT2mI90T,iv:tEVJZUgjDMY0IvflKejRVL14F3xrjdWaJU6de8ZPx3Y=,tag:Q5NwvG5Rp7Ca0NWlfRCciQ==,type:str]
    PORT: ENC[AES256_GCM,data:TWx21g==,iv:FE0lL9pL8F5ZhDqHVvXRem7jPg7rgaFE3fBeRofH9wk=,tag:tIpms6EdtVqDemlUHJcliA==,type:int]
    #ENC[AES256_GCM,data:tHGF4g55cSNtxhh8wzFgBH0/VLHCVT63Vw==,iv:AS3+180cWxEY8XqMArVMQpj7eKz+t/tOhA50SzSgVa8=,tag:9cqnyhbJj/mrBBe9TmZ6Kg==,type:comment]
    #ENC[AES256_GCM,data:gNWS55UWitOgQWxiOpSQ9QaLl2S3ntIFteAx/AOX0N8=,iv:HLatAExF/gdM+E0+R03ZsiUADaTEMZF9cmsXOz28VoE=,tag:kP1uBq6+ukNONRyPf16SqA==,type:comment]
    #ENC[AES256_GCM,data:1RSsOlW62Q5IlV9HxNnOFYoU8c1bA/fTYyVqQ5LHpzWOk9s=,iv:I94mmAoU7JTIr5dg2sudqe+/hdhWHXg9+D0zz3Ww4dA=,tag:Tt7QUeCmTmm0f6Xz2LMMVQ==,type:comment]
    #ENC[AES256_GCM,data:nUwQppxOTQcT5u5J55bqLk2vVrLgMwltz/wT/25tZ1pgMUXoTdBS0deaLesHtHln48rAcj3R5ASRTFfVFPgZfFs=,iv:fOJaCvLfr0wyT6IVGedAiOJtF8ZSC1nHkSUURpHVncE=,tag:DJqbF+yjLjP/iJe798LJBA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whte605qwe7e5rkt0dscfr9ea4fcqfzrqhdz0phk2v6vckmftqlsmmwy5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5djdmNWRybnZmNWxEUC8v
            MnhXMjZ0NVpQb3dycVEvNER6cUMxdWJER3lzClg3RDNWUFlLS2VsQTlqS0FwN2Jn
            Vnl6aUdvQmZwZDBMTUFoRTUwUEg2V1kKLS0tIFZiOU1xOUpHeHh4S1c2U0FOYTNJ
            Q3hWRkNwSGd2eEhjYmVBRVZQdGNmbTQKgKI6/l4uQrfmdO/4sjGsvn2b1yYu0EyR
            bswvpfoEUmT0Hp5K3NBZzfSLb+B+th2TgFfbLgfT3mvzCyMIeK8iHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T16:39:09Z"
    mac: ENC[AES256_GCM,data:nDzSf1HR8zMGWzbBqrTKlud2cEDVJPbD2NM/wQaEWoqo3U/kifNlOtoBh3FJix0985Q66jzYpAZap2Zmi7+lAldSNwTsaP8ji8E57y6BnqKXOd/t1rFIqp1SUv8AjUy6xaHkxyOmVG2m4VxyaAqU3jjhuNitb0sYUsQp2X8bK8E=,iv:i0XeDYhYVqjhsbMAsIgLw45yCcpGCB9XHae6aUfW0NY=,tag:+BZotayZiD4ixAnWvQ3Xfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
