apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-coder-db
  namespace: tool
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn